name: Build & Push Docker Image

on:
  # push:
  #   branches:
  #     - main
  #     - master

  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      tag:
        description: Docker Tag
        required: false
        default: latest

permissions:
  contents: read
  packages: write

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mcgtekwrt/lunatv-armv7
            ghcr.io/${{ github.repository_owner }}/lunatv-armv7

          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}

      - name: Build & Push
        uses: docker/build-push-action@v6

        with:

          context: .

          file: Dockerfile

          platforms: linux/arm/v7

          push: true

          tags: ${{ steps.meta.outputs.tags }}

          labels: ${{ steps.meta.outputs.labels }}

          cache-from: type=gha

          cache-to: type=gha,mode=max

          provenance: false

          sbom: false
